---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users:
          - vagrant
    openssh:
      server:
        password_authentication: "yes"
    users:
      - vagrant

platforms:
  - name: ubuntu-15.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-8.1
  - name: centos-7.1
  # - name: macosx-10.9
  #   driver:
  #     box: chef/macosx-10.9 # private box
  # - name: macosx-10.10
  #   driver:
  #     box: chef/macosx-10.10 # private box

suites:
- name: default
  run_list:
    - recipe[ut_workstation]
