---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[ut_workstation]
  attributes:
    ut_workstation:
      install_virtualbox: false
    users:
    - jdoe
