---
driver:
  name: vagrant

platforms:
- name: ubuntu-13.04
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[ut_workstation]
  attributes:
    ut_workstation:
      install_virtualbox: false
      install_vagrant: false
    users:
    - vagrant
