#!/usr/bin/env ruby

site "https://supermarket.getchef.com/api/v1"

cookbook "ut_workstation",
  :path => "."

cookbook "bashrc",
  :git => "https://github.com/fnichol/chef-bashrc.git",
  :ref => "v0.3.4"

# pending merge of https://github.com/chef-osx/xcode/pull/5
# and next release
cookbook "xcode",
  :git => "https://github.com/fnichol/xcode.git",
  :ref => "mac-1010-109-updates"

# pending merge of https://github.com/chef-osx/xquartz/pull/6
# and next release
cookbook "xquartz",
  :git => "https://github.com/fnichol/xquartz-cookbook.git",
  :ref => "macosx-10.10"
