name             "ut_workstation"
maintainer       "Fletcher Nichol"
maintainer_email "fnichol@nichol.ca"
license          "Apache 2.0"
description      "Unicorn Tears Workstation"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"

supports "mac_os_x"
supports "ubuntu"
supports "debian"

depends "apt"
depends "bashrc"
depends "chruby"
depends "dmg"
depends "homebrew"
depends "homesick"
depends "mac_os_x"
depends "user"
depends "python"
depends "xquartz"
depends "vagrant"
depends "virtualbox"
depends "zip_app"
